imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru
    app.locales: en|ru|am

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
#     translator: { fallbacks: [en,ru,am] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'ToolBoxFileBrowserBundle:form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    registration:
        confirmation:
            enabled: false
        form:
          type: AppBundle\Form\RegistrationType

    from_email:
        address: '%mailer_user%'
        sender_name: "Toolbox"
    resetting:
        email:
            from_email:
                address:     '%mailer_user%'
                sender_name: Toolbox


sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_admin:
    options:
      html5_validate:    true     # enable or disable html5 form validation
      confirm_exit:      true     # enable or disable a confirmation before navigating away
      use_select2:       true     # enable or disable usage of the Select2 jQuery library
      use_icheck:        true     # enable or disable usage of the iCheck library
      use_bootlint:      false    # enable or disable usage of Bootlint
      use_stickyforms:   true     # enable or disable the floating buttons
      form_type:         standard # can also be 'horizontal'

    templates:
        layout: SonataAdminBundle::layout.html.twig
        edit:              '@SonataAdmin/CRUD/edit.html.twig'
        tab_menu_template: '@SonataAdmin/Core/tab_menu_template.html.twig'
    global_search:
        empty_boxes: fade

stof_doctrine_extensions:
    orm:
        default:
            sluggable:   true
            translatable: true
    class:
        translatable: Gedmo\Translatable\TranslatableListener
        sluggable: Gedmo\Sluggable\SluggableListener

sonata_translation:
    locales: [en,ru,am]
    default_locale: '%locale%'
    # here enable the types you need
    gedmo:
        enabled: true
    knplabs:
        enabled: false

tool_box_file_browser:
    max_file_size: 5000000
    file_types:
            [
                'image/gif',
                'image/png',
                'image/jpeg',
                'image/pjpeg',
                'image/svg+xml',
                'image/tiff',
                'image/x-tiff',
                'image/tiff',
                'image/x-tiff',
                'application/octet-stream',
                'application/pdf',
                'application/postscript',
                'application/x-troff-msvideo',
                'video/avi',
                'video/mp4',
                'video/msvideo',
                'video/x-msvideo',
                'application/msword',
                'text/html',
                'application/x-javascript',
                'application/javascript',
                'application/ecmascript',
                'text/javascript',
                'text/ecmascript',
                'video/quicktime',
                'audio/mpeg3',
                'audio/x-mpeg-3',
                'video/mpeg',
                'video/x-mpeg',
                'text/plain',
                'application/excel',
                'application/vnd.ms-excel',
                'application/x-excel',
                'application/x-msexcel',
                'application/zip',
                'application/x-rar',
            ]
    no_image_file: /img/no-image.jpg
    default_upload_dir: /img

knp_paginator:
  page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
  default_options:
    page_name: page                 # page query parameter name
    sort_field_name: sort           # sort field query parameter name
    sort_direction_name: direction  # sort direction query parameter name
    distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
    filter_field_name: filterField  # filter field query parameter name
    filter_value_name: filterValue  # filter value query parameter name
  template:
    pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
    filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template

